version: 2.1

jobs:
  publish_site:
    docker:
      - image: ayazhafiz/ocaml4lang
    steps:
      - checkout
      - run: eval $(opam env) && ./www/build.sh
      - run: mkdir -p /tmp
      - run: cp -r www /tmp/docs
      - run: |
            git reset --hard HEAD
            git config --global user.email "builds@circleci.com"
            git config --global user.name "CircleCI"
            git remote add circleorigin https://${GH_TOKEN}@github.com/ayazhafiz/lang_narrow
            git checkout gh-pages
            rm -rf *
            mv /tmp/docs/* .
            git add -f .
            if git commit -m "CircleCI build $CIRCLE_BUILD_NUM" ; then
              git push -fq circleorigin
              echo -e "Deploy completed\n"
            else
              echo "Content not changed, nothing to deploy"
            fi          

workflows:
  publish_site:
    jobs:
      - publish_site:
          filters:
            branches:
              only: [ base ]
